// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define BOOKERLY_12_FONT_ID (-1905494168)
#define BOOKERLY_14_FONT_ID (1233852315)
#define BOOKERLY_16_FONT_ID (1588566790)
#define BOOKERLY_18_FONT_ID (681638548)
#define NOTOSANS_12_FONT_ID (-1559651934)
#define NOTOSANS_14_FONT_ID (-1014561631)
#define NOTOSANS_16_FONT_ID (-1422711852)
#define NOTOSANS_18_FONT_ID (1237754772)
#define OPENDYSLEXIC_8_FONT_ID (1331369208)
#define OPENDYSLEXIC_10_FONT_ID (-1374689004)
#define OPENDYSLEXIC_12_FONT_ID (-795539541)
#define OPENDYSLEXIC_14_FONT_ID (-1676627620)
#define UI_10_FONT_ID (-1246724383)
#define UI_12_FONT_ID (-359249323)
#define SMALL_FONT_ID (1073217904)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(BOOKERLY_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BOOKERLY_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BOOKERLY_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BOOKERLY_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(OPENDYSLEXIC_8_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(OPENDYSLEXIC_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(OPENDYSLEXIC_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(OPENDYSLEXIC_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
